services:
  be-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-auth-service
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - .:/app
    networks:
      - global_network

networks:
  global_network:
    external: true
