services:
  be-auth-service:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: be-auth-service
    restart: unless-stopped
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - .:/app
      - ./proto:/proto
    networks:
      - global_network

networks:
  global_network:
    external: true
